// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankServices.proto

package ma.elma_dev.stubs;

public final class BankServices {
  private BankServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface messageReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messageReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string messageFrom = 1;</code>
     * @return The messageFrom.
     */
    java.lang.String getMessageFrom();
    /**
     * <code>string messageFrom = 1;</code>
     * @return The bytes for messageFrom.
     */
    com.google.protobuf.ByteString
        getMessageFromBytes();

    /**
     * <code>string messageTo = 2;</code>
     * @return The messageTo.
     */
    java.lang.String getMessageTo();
    /**
     * <code>string messageTo = 2;</code>
     * @return The bytes for messageTo.
     */
    com.google.protobuf.ByteString
        getMessageToBytes();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code messageReq}
   */
  public  static final class messageReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messageReq)
      messageReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use messageReq.newBuilder() to construct.
    private messageReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private messageReq() {
      messageFrom_ = "";
      messageTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new messageReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private messageReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messageTo_ = s;
              break;
            }
            case 25: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.elma_dev.stubs.BankServices.internal_static_messageReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.elma_dev.stubs.BankServices.internal_static_messageReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.elma_dev.stubs.BankServices.messageReq.class, ma.elma_dev.stubs.BankServices.messageReq.Builder.class);
    }

    public static final int MESSAGEFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageFrom_;
    /**
     * <code>string messageFrom = 1;</code>
     * @return The messageFrom.
     */
    public java.lang.String getMessageFrom() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string messageFrom = 1;</code>
     * @return The bytes for messageFrom.
     */
    public com.google.protobuf.ByteString
        getMessageFromBytes() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETO_FIELD_NUMBER = 2;
    private volatile java.lang.Object messageTo_;
    /**
     * <code>string messageTo = 2;</code>
     * @return The messageTo.
     */
    public java.lang.String getMessageTo() {
      java.lang.Object ref = messageTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageTo_ = s;
        return s;
      }
    }
    /**
     * <code>string messageTo = 2;</code>
     * @return The bytes for messageTo.
     */
    public com.google.protobuf.ByteString
        getMessageToBytes() {
      java.lang.Object ref = messageTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageFrom_);
      }
      if (!getMessageToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageTo_);
      }
      if (amount_ != 0D) {
        output.writeDouble(3, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageFrom_);
      }
      if (!getMessageToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageTo_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.elma_dev.stubs.BankServices.messageReq)) {
        return super.equals(obj);
      }
      ma.elma_dev.stubs.BankServices.messageReq other = (ma.elma_dev.stubs.BankServices.messageReq) obj;

      if (!getMessageFrom()
          .equals(other.getMessageFrom())) return false;
      if (!getMessageTo()
          .equals(other.getMessageTo())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEFROM_FIELD_NUMBER;
      hash = (53 * hash) + getMessageFrom().hashCode();
      hash = (37 * hash) + MESSAGETO_FIELD_NUMBER;
      hash = (53 * hash) + getMessageTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.elma_dev.stubs.BankServices.messageReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.elma_dev.stubs.BankServices.messageReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messageReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messageReq)
        ma.elma_dev.stubs.BankServices.messageReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.elma_dev.stubs.BankServices.internal_static_messageReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.elma_dev.stubs.BankServices.internal_static_messageReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.elma_dev.stubs.BankServices.messageReq.class, ma.elma_dev.stubs.BankServices.messageReq.Builder.class);
      }

      // Construct using ma.elma_dev.stubs.BankServices.messageReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageFrom_ = "";

        messageTo_ = "";

        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.elma_dev.stubs.BankServices.internal_static_messageReq_descriptor;
      }

      @java.lang.Override
      public ma.elma_dev.stubs.BankServices.messageReq getDefaultInstanceForType() {
        return ma.elma_dev.stubs.BankServices.messageReq.getDefaultInstance();
      }

      @java.lang.Override
      public ma.elma_dev.stubs.BankServices.messageReq build() {
        ma.elma_dev.stubs.BankServices.messageReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.elma_dev.stubs.BankServices.messageReq buildPartial() {
        ma.elma_dev.stubs.BankServices.messageReq result = new ma.elma_dev.stubs.BankServices.messageReq(this);
        result.messageFrom_ = messageFrom_;
        result.messageTo_ = messageTo_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.elma_dev.stubs.BankServices.messageReq) {
          return mergeFrom((ma.elma_dev.stubs.BankServices.messageReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.elma_dev.stubs.BankServices.messageReq other) {
        if (other == ma.elma_dev.stubs.BankServices.messageReq.getDefaultInstance()) return this;
        if (!other.getMessageFrom().isEmpty()) {
          messageFrom_ = other.messageFrom_;
          onChanged();
        }
        if (!other.getMessageTo().isEmpty()) {
          messageTo_ = other.messageTo_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.elma_dev.stubs.BankServices.messageReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.elma_dev.stubs.BankServices.messageReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageFrom_ = "";
      /**
       * <code>string messageFrom = 1;</code>
       * @return The messageFrom.
       */
      public java.lang.String getMessageFrom() {
        java.lang.Object ref = messageFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @return The bytes for messageFrom.
       */
      public com.google.protobuf.ByteString
          getMessageFromBytes() {
        java.lang.Object ref = messageFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @param value The messageFrom to set.
       * @return This builder for chaining.
       */
      public Builder setMessageFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageFrom() {
        
        messageFrom_ = getDefaultInstance().getMessageFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @param value The bytes for messageFrom to set.
       * @return This builder for chaining.
       */
      public Builder setMessageFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageTo_ = "";
      /**
       * <code>string messageTo = 2;</code>
       * @return The messageTo.
       */
      public java.lang.String getMessageTo() {
        java.lang.Object ref = messageTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageTo = 2;</code>
       * @return The bytes for messageTo.
       */
      public com.google.protobuf.ByteString
          getMessageToBytes() {
        java.lang.Object ref = messageTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageTo = 2;</code>
       * @param value The messageTo to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageTo() {
        
        messageTo_ = getDefaultInstance().getMessageTo();
        onChanged();
        return this;
      }
      /**
       * <code>string messageTo = 2;</code>
       * @param value The bytes for messageTo to set.
       * @return This builder for chaining.
       */
      public Builder setMessageToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageTo_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messageReq)
    }

    // @@protoc_insertion_point(class_scope:messageReq)
    private static final ma.elma_dev.stubs.BankServices.messageReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.elma_dev.stubs.BankServices.messageReq();
    }

    public static ma.elma_dev.stubs.BankServices.messageReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<messageReq>
        PARSER = new com.google.protobuf.AbstractParser<messageReq>() {
      @java.lang.Override
      public messageReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new messageReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<messageReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<messageReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.elma_dev.stubs.BankServices.messageReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface messageRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messageResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string messageFrom = 1;</code>
     * @return The messageFrom.
     */
    java.lang.String getMessageFrom();
    /**
     * <code>string messageFrom = 1;</code>
     * @return The bytes for messageFrom.
     */
    com.google.protobuf.ByteString
        getMessageFromBytes();

    /**
     * <code>string messgaeResp = 2;</code>
     * @return The messgaeResp.
     */
    java.lang.String getMessgaeResp();
    /**
     * <code>string messgaeResp = 2;</code>
     * @return The bytes for messgaeResp.
     */
    com.google.protobuf.ByteString
        getMessgaeRespBytes();

    /**
     * <code>float amount = 3;</code>
     * @return The amount.
     */
    float getAmount();

    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    double getResult();
  }
  /**
   * Protobuf type {@code messageResp}
   */
  public  static final class messageResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messageResp)
      messageRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use messageResp.newBuilder() to construct.
    private messageResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private messageResp() {
      messageFrom_ = "";
      messgaeResp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new messageResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private messageResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messgaeResp_ = s;
              break;
            }
            case 29: {

              amount_ = input.readFloat();
              break;
            }
            case 33: {

              result_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.elma_dev.stubs.BankServices.internal_static_messageResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.elma_dev.stubs.BankServices.internal_static_messageResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.elma_dev.stubs.BankServices.messageResp.class, ma.elma_dev.stubs.BankServices.messageResp.Builder.class);
    }

    public static final int MESSAGEFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageFrom_;
    /**
     * <code>string messageFrom = 1;</code>
     * @return The messageFrom.
     */
    public java.lang.String getMessageFrom() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string messageFrom = 1;</code>
     * @return The bytes for messageFrom.
     */
    public com.google.protobuf.ByteString
        getMessageFromBytes() {
      java.lang.Object ref = messageFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSGAERESP_FIELD_NUMBER = 2;
    private volatile java.lang.Object messgaeResp_;
    /**
     * <code>string messgaeResp = 2;</code>
     * @return The messgaeResp.
     */
    public java.lang.String getMessgaeResp() {
      java.lang.Object ref = messgaeResp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messgaeResp_ = s;
        return s;
      }
    }
    /**
     * <code>string messgaeResp = 2;</code>
     * @return The bytes for messgaeResp.
     */
    public com.google.protobuf.ByteString
        getMessgaeRespBytes() {
      java.lang.Object ref = messgaeResp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messgaeResp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private float amount_;
    /**
     * <code>float amount = 3;</code>
     * @return The amount.
     */
    public float getAmount() {
      return amount_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private double result_;
    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    public double getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageFrom_);
      }
      if (!getMessgaeRespBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messgaeResp_);
      }
      if (amount_ != 0F) {
        output.writeFloat(3, amount_);
      }
      if (result_ != 0D) {
        output.writeDouble(4, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageFrom_);
      }
      if (!getMessgaeRespBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messgaeResp_);
      }
      if (amount_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, amount_);
      }
      if (result_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.elma_dev.stubs.BankServices.messageResp)) {
        return super.equals(obj);
      }
      ma.elma_dev.stubs.BankServices.messageResp other = (ma.elma_dev.stubs.BankServices.messageResp) obj;

      if (!getMessageFrom()
          .equals(other.getMessageFrom())) return false;
      if (!getMessgaeResp()
          .equals(other.getMessgaeResp())) return false;
      if (java.lang.Float.floatToIntBits(getAmount())
          != java.lang.Float.floatToIntBits(
              other.getAmount())) return false;
      if (java.lang.Double.doubleToLongBits(getResult())
          != java.lang.Double.doubleToLongBits(
              other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEFROM_FIELD_NUMBER;
      hash = (53 * hash) + getMessageFrom().hashCode();
      hash = (37 * hash) + MESSGAERESP_FIELD_NUMBER;
      hash = (53 * hash) + getMessgaeResp().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResult()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.elma_dev.stubs.BankServices.messageResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.elma_dev.stubs.BankServices.messageResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messageResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messageResp)
        ma.elma_dev.stubs.BankServices.messageRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.elma_dev.stubs.BankServices.internal_static_messageResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.elma_dev.stubs.BankServices.internal_static_messageResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.elma_dev.stubs.BankServices.messageResp.class, ma.elma_dev.stubs.BankServices.messageResp.Builder.class);
      }

      // Construct using ma.elma_dev.stubs.BankServices.messageResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageFrom_ = "";

        messgaeResp_ = "";

        amount_ = 0F;

        result_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.elma_dev.stubs.BankServices.internal_static_messageResp_descriptor;
      }

      @java.lang.Override
      public ma.elma_dev.stubs.BankServices.messageResp getDefaultInstanceForType() {
        return ma.elma_dev.stubs.BankServices.messageResp.getDefaultInstance();
      }

      @java.lang.Override
      public ma.elma_dev.stubs.BankServices.messageResp build() {
        ma.elma_dev.stubs.BankServices.messageResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.elma_dev.stubs.BankServices.messageResp buildPartial() {
        ma.elma_dev.stubs.BankServices.messageResp result = new ma.elma_dev.stubs.BankServices.messageResp(this);
        result.messageFrom_ = messageFrom_;
        result.messgaeResp_ = messgaeResp_;
        result.amount_ = amount_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.elma_dev.stubs.BankServices.messageResp) {
          return mergeFrom((ma.elma_dev.stubs.BankServices.messageResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.elma_dev.stubs.BankServices.messageResp other) {
        if (other == ma.elma_dev.stubs.BankServices.messageResp.getDefaultInstance()) return this;
        if (!other.getMessageFrom().isEmpty()) {
          messageFrom_ = other.messageFrom_;
          onChanged();
        }
        if (!other.getMessgaeResp().isEmpty()) {
          messgaeResp_ = other.messgaeResp_;
          onChanged();
        }
        if (other.getAmount() != 0F) {
          setAmount(other.getAmount());
        }
        if (other.getResult() != 0D) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.elma_dev.stubs.BankServices.messageResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.elma_dev.stubs.BankServices.messageResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageFrom_ = "";
      /**
       * <code>string messageFrom = 1;</code>
       * @return The messageFrom.
       */
      public java.lang.String getMessageFrom() {
        java.lang.Object ref = messageFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @return The bytes for messageFrom.
       */
      public com.google.protobuf.ByteString
          getMessageFromBytes() {
        java.lang.Object ref = messageFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @param value The messageFrom to set.
       * @return This builder for chaining.
       */
      public Builder setMessageFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageFrom() {
        
        messageFrom_ = getDefaultInstance().getMessageFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string messageFrom = 1;</code>
       * @param value The bytes for messageFrom to set.
       * @return This builder for chaining.
       */
      public Builder setMessageFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messgaeResp_ = "";
      /**
       * <code>string messgaeResp = 2;</code>
       * @return The messgaeResp.
       */
      public java.lang.String getMessgaeResp() {
        java.lang.Object ref = messgaeResp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messgaeResp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messgaeResp = 2;</code>
       * @return The bytes for messgaeResp.
       */
      public com.google.protobuf.ByteString
          getMessgaeRespBytes() {
        java.lang.Object ref = messgaeResp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messgaeResp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messgaeResp = 2;</code>
       * @param value The messgaeResp to set.
       * @return This builder for chaining.
       */
      public Builder setMessgaeResp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messgaeResp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messgaeResp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessgaeResp() {
        
        messgaeResp_ = getDefaultInstance().getMessgaeResp();
        onChanged();
        return this;
      }
      /**
       * <code>string messgaeResp = 2;</code>
       * @param value The bytes for messgaeResp to set.
       * @return This builder for chaining.
       */
      public Builder setMessgaeRespBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messgaeResp_ = value;
        onChanged();
        return this;
      }

      private float amount_ ;
      /**
       * <code>float amount = 3;</code>
       * @return The amount.
       */
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>float amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(float value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0F;
        onChanged();
        return this;
      }

      private double result_ ;
      /**
       * <code>double result = 4;</code>
       * @return The result.
       */
      public double getResult() {
        return result_;
      }
      /**
       * <code>double result = 4;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(double value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double result = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messageResp)
    }

    // @@protoc_insertion_point(class_scope:messageResp)
    private static final ma.elma_dev.stubs.BankServices.messageResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.elma_dev.stubs.BankServices.messageResp();
    }

    public static ma.elma_dev.stubs.BankServices.messageResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<messageResp>
        PARSER = new com.google.protobuf.AbstractParser<messageResp>() {
      @java.lang.Override
      public messageResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new messageResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<messageResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<messageResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.elma_dev.stubs.BankServices.messageResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messageReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messageReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messageResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messageResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022bankServices.proto\"D\n\nmessageReq\022\023\n\013me" +
      "ssageFrom\030\001 \001(\t\022\021\n\tmessageTo\030\002 \001(\t\022\016\n\006am" +
      "ount\030\003 \001(\001\"W\n\013messageResp\022\023\n\013messageFrom" +
      "\030\001 \001(\t\022\023\n\013messgaeResp\030\002 \001(\t\022\016\n\006amount\030\003 " +
      "\001(\002\022\016\n\006result\030\004 \001(\0012\320\001\n\014bankServices\022$\n\007" +
      "convert\022\013.messageReq\032\014.messageResp\0220\n\021ge" +
      "tCurrencyStream\022\013.messageReq\032\014.messageRe" +
      "sp0\001\0223\n\024perfomCurrencyStream\022\013.messageRe" +
      "q\032\014.messageResp(\001\0223\n\022fullCurrencyStream\022" +
      "\013.messageReq\032\014.messageResp(\0010\001B\023\n\021ma.elm" +
      "a_dev.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messageReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messageReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messageReq_descriptor,
        new java.lang.String[] { "MessageFrom", "MessageTo", "Amount", });
    internal_static_messageResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messageResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messageResp_descriptor,
        new java.lang.String[] { "MessageFrom", "MessgaeResp", "Amount", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
